spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:mem:watcher
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:
    username: sa
    password:

  jackson:
    default-property-inclusion: non_null
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
    serialization:
      write-dates-as-timestamps: false

  cache:
    cache-names: cryptocurrency
    caffeine.spec: maximumSize=1000,expireAfterAccess=60s

logging:
  level:
    root: WARN
    com.idfinance.cryptocurrencywatcher: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

springdoc:
  swagger-ui:
    operations-sorter: method